version: '3.8'

services:
    db:
        image: postgres:latest
        container_name: matesbot-db
        ports:
            - "5433:5432"
        environment:
            POSTGRES_HOST_AUTH_METHOD: "trust"
        volumes:
            - postgres_data:/var/lib/postgresql/data/
        restart: on-failure
    bot:
        build: .
        container_name: matesbot
        volumes:
            -   .:/matesbot/
        depends_on:
            - db
        restart: on-failure
    adminer:
        image: adminer
        container_name: matesbot-adminer
        ports:
            - "8081:8080"
        depends_on:
            - db
        restart: on-failure

volumes:
    postgres_data:
